### ISSUE TITLE
Tag it ?

### ISSUE THREAD

**Issue by ruscon** [sixdayz/OpcacheBundle#10]
> - The requested package sixdays/opcache-bundle master is satisfiable by sixdays/opcache-bundle[dev-master] but these conflict with your requirements or minimum-stability.

Can u add first tag ?

**Comment by secit-pl** [comment]
Could you add a tag?

**Comment by sixdayz** [comment]
complete! :)

**Comment by secit-pl** [comment]
Thank you :)

**Comment by sixdayz** [comment]
No problem! Sorry for taking so long :)
