### ISSUE TITLE
command not working

### ISSUE THREAD

**Issue by schoren** [sixdayz/OpcacheBundle#7]
I been testing this command (which is great BTW, thanks!), and it seems that, at least on my box, CURLing to an IP using the Host header doesn't make Nginx realize what virtualhost you are trying to access.

I think the easiest fix for this (which can also add a lot of flexibility) is the following:

Remove the IP, hostname, and protocol settings, add a new base_url setting (where you can use both an IP or a hostname, using port or not, http/s, just like you do in a browser), and update the command to work with this.

I'm making a pull request with this fix, so if you like it you can merge it.

Thanks!

**Comment by sixdayz** [comment]
Thank you ;)
